#!/bin/bash -x

'function fix_cfn_init {\n',
'  # Setup CFN init and signal\n',
'  CFN_INIT=$(rpm -ql aws-cfn-bootstrap | grep cfn-init$)\n',
'  test_cfn_init_rc=$?\n',
'\n',
'  if [[ ! "$test_cfn_init_rc" = 0 ]]; then\n',
'      if [[ "$operating_system" = "rhel7" ]]; then\n',
'          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm\n',
'      else\n',
'          yum install epel-release -y\n',
'      fi\n',
'\n',
'      yum install pystache python-daemon python-setuptools -y\n',
'      curl -O https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.amzn1.noarch.rpm\n',
'      rpm -ivh aws-cfn-bootstrap-latest.amzn1.noarch.rpm\n',
'    export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages\n',
'  fi\n',
'}\n',